### ISSUE TITLE
Calibre can't use system launchers/apps to open books

### ISSUE THREAD

**Issue by terzag** [flathub/com.calibre_ebook.calibre#63]
Hello,
I've been using Calibre from flathub for a while on Xubuntu. I manage e-books in different formats in my library: EPUB, PDF, CBR/CBZ. I want to open them with different applications: Calibre e-book viewer (EPUB), Atril (PDF) and MComix (CBR/CBZ). These associations are setup outside of Calibre and work fine when opening documents through the file manager.

On Xubuntu 20.04, everything worked fine: double-clicking on an e-book in Calibre opened it with the right app. Since I've upgraded to Xubuntu 20.10, it doesn't work anymore: double-clicking on a PDF or a CBR/CBZ in Calibre just does nothing. There's the animation showing that it's trying to open the book but that's all that happens. Opening them with the Calibre e-book viewer (that's bundled with Calibre in the flatpak) works, though.

If I choose the option to view a specific version of a book to be able to access the list of applications to open it with, only Calibre and it's e-book viewer are listed. I can manually add a system app by looking for its binary but it doesn't work either (as a sidenote, I can't point to MComix as it's a Python app and Calibre tells me that it's not a binary). Can't point to the launchers in /usr/share/applications either (not binaries).

I've asked for help on a forum and someone confirmed the issue with Calibre on Arch Linux. Pointed out that Dolphin (as a flatpak) uses a "portal" to open files through external apps and that Calibre should use a similar solution. The problem being likely that the current version of flatpak is more sandboxed (and that would be why it worked fine in Xubuntu 20.04 but not in 20.10 anymore).

**Comment by Erick555** [comment]
Duplicate of https://github.com/flathub/com.calibre_ebook.calibre/issues/50 and https://github.com/flathub/com.calibre_ebook.calibre/issues/39 . Will be fixed next calibre upstream update.

**Comment by ghisvail** [comment]
@terzag please let us know whether the latest update fixed it for you.

**Comment by terzag** [comment]
Just updated, issue seems to be fixed as CBR/CBZ and PDF open with the usual softwares.

There's just one thing I'm not sure about: if I select a book and want to visualize a specific format to get access to the list of softwares, when choosing "open with", I still see only Calibre and Calibre e-book viewer. I don't remember if it was different with older versions and it displayed a list of softwares or not.

**Comment by Erick555** [comment]
I have the same issue when I try opening pdf file through portal in any flatpak app (and 99% of time I don't want to open pdf with calibre). I don't know why calibre is always the chosen one for those filetypes (something wrong with mimetypes listed in desktop?) but at least in kde I can closk "Show more" button at bottom to open file with any other app I like (I don't know if same is true in gtk version of portal.

**Comment by Erick555** [comment]
@terzag  You should see list of all apps that declare handling of specific filetype in their desktop files. You may need to run `sudo update-desktop-database` or `update-desktop-database ~/.local/share/applications` to refresh that list. In kde it's also possible to click _Show more_ button at bottom to open file with any other app (I don't know if same is true in gtk version of portal. Anyway issue from this ticket is fixed.

**Comment by ghisvail** [comment]
I am closing this then.

**Comment by terzag** [comment]
> @terzag You should see list of all apps that declare handling of specific filetype in their desktop files. You may need to run `sudo update-desktop-database` or `update-desktop-database ~/.local/share/applications` to refresh that list. In kde it's also possible to click _Show more_ button at bottom to open file with any other app (I don't know if same is true in gtk version of portal. Anyway issue from this ticket is fixed.

Well, that doesn't seem to be the case. I've just tried both update-desktop-database commands and Calibre still shows me only Calibre and Calibre e-book viewer when selecting e.g. "Open CBR with..."
Outside of Calibre, CBR also have Atril and Engrampa set as possible softwares.

Should I open a new report?

**Comment by Erick555** [comment]
No, this shouldn't depend on calibre flatpak. You may try asking about it in https://github.com/flatpak/xdg-desktop-portal/issues
